name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "11"
        
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ github.event.inputs.jdkVersion }}
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Releasing using Hub
      uses: r0user/release-apk@main
      env:
       GITHUB_TOKEN: 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
       APP_FOLDER: app
